package vmodev.clearkeep.fragments.Interfaces

import androidx.fragment.app.Fragment

interface IFragment {
    fun getFragment(): Fragment;

    companion object {
        const val LOGIN_FRAGMENT = "LOGIN_FRAGMENT";
        const val SIGNUP_FRAGMENT = "SIGNUP_FRAGMENT";
        const val PASSPHRASE_RESTORE_BACK_UP_KEY_FRAGMENT = "PASSPHRASE_RESTORE_BACK_UP_KEY_FRAGMENT";
        const val TEXT_FILE_RESTORE_BACK_UP_KEY_FRAGMENT = "TEXT_FILE_RESTORE_BACK_UP_KEY_FRAGMENT";
        const val HANDLER_VERIFY_EMAIL_FRAGMENT = "HANDLER_VERIFY_EMAIL_FRAGMENT";
        const val FORGOT_PASSWORD_FRAGMENT = "FORGOT_PASSWORD_FRAGMENT";
        const val FORGOT_PASSWORD_VERIFY_EMAIL_FRAGMENT = "FORGOT_PASSWORD_VERIFY_EMAIL_FRAGMENT";
        const val SEARCH_MESSAGE_FRAGMENT = "SEARCH_MESSAGE_FRAGMENT";
        const val SEARCH_ROOM_FRAGMENT = "SEARCH_ROOM_FRAGMENT";
        const val SEARCH_PEOPLE_FRAGMENT = "SEARCH_PEOPLE_FRAGMENT";
        const val SEARCH_FILES_FRAGMENT = "SEARCH_FILES_FRAGMENT";
        const val HOME_SCREEN_FRAGMENT = "HOME_SCREEN_FRAGMENT";
        const val FAVOURITES_FRAGMENT = "FAVOURITES_FRAGMENT";
        const val CONTACTS_FRAGMENT = "CONTACTS_FRAGMENT";
        const val LIST_ROOM_FRAGMENT = "LIST_ROOM_FRAGMENT";
        const val BACKUP_KEY_MANAGE_FRAGMENT = "BACKUP_KEY_MANAGE_FRAGMENT";
    }
}