package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractCallSettingActivityViewModel

interface ICallSettingsActivityViewModelFactory : IViewModelFactory<AbstractCallSettingActivityViewModel> {
}