package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractCallHistoryViewModel

interface ICallHistoryViewModelFactory: IViewModelFactory<AbstractCallHistoryViewModel>{
}