package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractChangeThemeActivityViewModel

interface IChangeThemeActivityViewModelFactory : IViewModelFactory<AbstractChangeThemeActivityViewModel> {
}