package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractCreateNewCallActivityViewModel

interface ICreateNewCallActivityViewModelFactory : IViewModelFactory<AbstractCreateNewCallActivityViewModel> {
}