package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractDirectMessageFragmentViewModel

interface IDirectMessageFragmentViewModelFactory : IViewModelFactory<AbstractDirectMessageFragmentViewModel> {
}