package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractEditProfileActivityViewModel

interface IEditProfileActivityViewModelFactory : IViewModelFactory<AbstractEditProfileActivityViewModel> {
}