package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractFavouritesFragmentViewModel

interface IFavouritesFragmentViewModelFactory : IViewModelFactory<AbstractFavouritesFragmentViewModel> {
}