package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.FeedBackFragmentViewModel
import vmodev.clearkeep.viewmodels.interfaces.AbstractFeedBackFragmentViewModel

interface IFeedBackViewModelFactory : IViewModelFactory<AbstractFeedBackFragmentViewModel> {
}