package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractHomeScreenActivityViewModel
import vmodev.clearkeep.viewmodels.interfaces.AbstractUserViewModel

interface IHomeScreenViewModelFactory : IViewModelFactory<AbstractHomeScreenActivityViewModel> {
}