package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractHomeScreenActivityViewModel

interface IHomeScreenViewModelFactory : IViewModelFactory<AbstractHomeScreenActivityViewModel>