package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractListRoomFragmentViewModel

interface IListRoomFragmentViewModelFactory : IViewModelFactory<AbstractListRoomFragmentViewModel> {
}