package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractMessageListActivityViewModel

interface IMessageListActivityViewModelFactory : IViewModelFactory<AbstractMessageListActivityViewModel> {
}