package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractNotificationSettingsActivityViewModel

interface INotificationSettingsActivityViewModelFactory : IViewModelFactory<AbstractNotificationSettingsActivityViewModel> {
}