package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractProfileSettingsActivityViewModel

interface IProfileSettingsActivityViewModelFactory : IViewModelFactory<AbstractProfileSettingsActivityViewModel> {
}