package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractRoomFileListActivityViewModel

interface IRoomFileListActivityViewModelFactory : IViewModelFactory<AbstractRoomFileListActivityViewModel> {
}