package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractUserInformationActivityViewModel

interface IUserInformationActivityViewModelFactory : IViewModelFactory<AbstractUserInformationActivityViewModel> {
}