package vmodev.clearkeep.factories.viewmodels.interfaces

import vmodev.clearkeep.viewmodels.interfaces.AbstractViewUserProfileActivityViewModel

interface IViewUserProfileActivityViewModelFactory : IViewModelFactory<AbstractViewUserProfileActivityViewModel> {
}